name: Tests

on:
  pull_request:
    types: [opened, review_requested]

jobs:
 Review:
   runs-on: ubuntu-latest
   steps:
      - uses: murs313/request-review@v1.0
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         reviewers: 'varmoh'
         pull-request-number: 1


 Merge:
    needs: Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BaharaJr/merge-pr@0.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                  
