name: Tests

on:
  pull_request:
    types: [opened, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: BaharaJr/merge-pr@0.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    
      - uses: murs313/request-review@v1.0
        with:
      # Reviewers to add, in space separated list.
          reviewers: 'varmoh'
    # Pull request's number to request review.
          pull-request-number: 1
