on: pull_request
jobs:
  automerge:
    - name: Merge
      uses: KeisukeYamashita/auto-pull-request-merge@v1
      with:
        intervalSeconds: 10
        timeoutSeconds: 30
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
