name: auto merge action
on:
  pull_request:
    types:
      - labeled
      - opened
jobs:
  autoMerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: buildsville/simple-merge@v1
        id: merge
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          method: 'squash'
          labels: '[ "foo", "bar" ]'
          title: 'commit title'
          message: 'commit message'
      - name: result
        run: |
          echo "result: ${{ steps.merge.outputs.result }}"
